after-login-command = []

after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

start-at-login = true

enable-normalization-flatten-containers = true

enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
  preset = 'qwerty'

[gaps]
  inner.horizontal = 10
  inner.vertical =   10
  outer.left =       10
  outer.bottom =     10
  outer.top =        10
  outer.right =      10

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # Navigation on right home row (standard ergonomic pattern)
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'
    
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'
    
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'

    # Terminal - Ghostty
    alt-enter = ['exec-and-forget open -n -a /Applications/Ghostty.app']

    # Browser - Google Chrome
    alt-b = ['exec-and-forget /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --new-window']
    alt-shift-b = ['exec-and-forget /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --new-window --incognito']

    # Chat - Slack
    alt-c = ['exec-and-forget open -a /Applications/Slack.app']
    # Teams - Microsoft Teams
    alt-shift-c = ['exec-and-forget open -a /Applications/Microsoft\ Teams.app']

    # Music - Spotify
    alt-m = ['exec-and-forget open -a /Applications/Spotify.app']

    # Email - Outlook
    alt-e = ['exec-and-forget open -a /Applications/Microsoft\ Outlook.app']

    # Finder
    alt-f = [
      '''exec-and-forget osascript -e '
      tell application "Finder"
          make new Finder window
          activate
      end tell'
      '''
    ]

    alt-a = ['exec-and-forget Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --new-window --app="https://claude.ai/new"']
    alt-t = ['exec-and-forget Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --new-window --app="https://app.todoist.com/app/upcoming"']
    alt-g = ['exec-and-forget Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --new-window --app="https://gmail.com"']

    alt-shift-f = 'fullscreen'
    
    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    
    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] 
    f = ['layout floating tiling', 'mode main'] 
    backspace = ['close-all-windows-but-current', 'mode main']
    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']
