after-login-command = []
after-startup-command = [
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

start-at-login = true

enable-normalization-flatten-containers = true

enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # Navigation on right home row (standard ergonomic pattern)
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'
    
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'
    
    # Terminal - Ghostty
    alt-enter = ['workspace T', 'exec-and-forget open -a /Applications/Ghostty.app']

    # Browser - Google Chrome
    alt-b = ['workspace B', 'exec-and-forget open -a /Applications/Google\ Chrome.app']
    alt-2 = ['workspace B', 'exec-and-forget open -a /Applications/Google\ Chrome.app']

    # Chat - Slack
    alt-c = ['workspace S', 'exec-and-forget open -a /Applications/Slack.app']
    alt-shift-1 = ['workspace S', 'exec-and-forget open -a /Applications/Slack.app']

    # Music - Spotify
    alt-m = ['workspace M', 'exec-and-forget open -a /Applications/Spotify.app']
    alt-shift-2 = ['workspace M', 'exec-and-forget open -a /Applications/Spotify.app']

    # Email - Outlook
    alt-e = ['workspace O', 'exec-and-forget open -a /Applications/Microsoft\ Outlook.app']
    alt-shift-3 = ['workspace O', 'exec-and-forget open -a /Applications/Microsoft\ Outlook.app']

    # Teams - Microsoft Teams
    alt-t = ['workspace C', 'exec-and-forget open -a /Applications/Microsoft\ Teams.app']
    alt-4 = ['move-node-to-workspace C', 'workspace C', 'exec-and-forget open -a /Applications/Microsoft\ Teams.app']

    alt-f = 'fullscreen'
    
    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    
    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] 
    f = ['layout floating tiling', 'mode main'] 
    backspace = ['close-all-windows-but-current', 'mode main']
    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ["move-node-to-workspace T"]

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace S"

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = "move-node-to-workspace O"

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace M"

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = "move-node-to-workspace C"
