#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}


echo "---------- dev-env ----------"

link_dir() {
  from=$1
  to=$2

  pushd $from > /dev/null
    dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    for dir in $dirs; do
      execute rm -rf $to/$dir
      execute ln -sf $from/$dir $to/$dir
    done
  popd > /dev/null
}

link_file() {
  from=$1
  to=$2
  name=$(basename $from)

  execute rm -f $to/$name
  execute ln -sf $script_dir/$from $to/$name
}

link_dir $script_dir/.config $HOME/.config

link_file .gitconfig $HOME
link_file .zshrc $HOME
link_file .tmux.conf $HOME
link_file .aerospace.toml $HOME
